# Generated by Django 5.2.5 on 2025-08-23 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=20)),
                ('father_email', models.EmailField(max_length=150)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_mobile', models.CharField(max_length=20)),
                ('mother_email', models.EmailField(max_length=150)),
                ('present_address', models.TextField(max_length=100)),
                ('permanent_address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('student_class', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('email', models.EmailField(max_length=150)),
                ('mobile_number', models.CharField(max_length=20)),
                ('fillier', models.CharField(max_length=100)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.parent')),
            ],
        ),
    ]
